# Generated by Django 3.0.6 on 2022-08-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitordata',
            name='visits',
        ),
        migrations.AddField(
            model_name='visitordata',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
